version: '3.4'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./bin:/code
            - ./web/site.conf:/etc/nginx/conf.d/default.conf
        user: root

    php:
        image: php:fpm
        volumes:
            - ./bin:/code
